
import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import Nav from '@/components/Nav'
import About from '@/components/About'
import Projects from '@/components/Projects'

export default function Home() {
  return (
    <div className='font-burtons'>
      <Head>
        <title>Austin Hollands Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white min-h-screen text-center ' >
        <Nav/>
        <section className=' '>
          <About/>       
        </section>

      {/* second page */}
        <section className=''>
          <Projects />
        </section>
      </main>
    </div>
  )
}
